# Generated by Django 4.2.5 on 2023-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='is_for_sell',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='sending',
        ),
        migrations.AddField(
            model_name='scrap',
            name='product_location',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='material',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Wood', 'Wood'), ('Glass', 'Glass'), ('Liquid', 'Liquid'), ('Powders', 'Powders'), ('Stones', 'Stones'), ('Others', 'Others')], max_length=20),
        ),
    ]
