# Generated by Django 4.2.5 on 2023-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_scrap_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='product_location',
            field=models.CharField(default='Some Default City', max_length=45),
        ),
    ]
