# Generated by Django 4.2.5 on 2023-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_scrap_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='category',
            field=models.CharField(choices=[('Quincaillerie', 'Quincaillerie'), ('Outils', 'Outils'), ('Peinture', 'Peinture'), ('Sol', 'Sol'), ('Electricité', 'Electricité'), ('Plomberie', 'Plomberie'), ('Toiture', 'Toiture'), ('Menuiserie', 'Menuiserie'), ('Gros-œuvre', 'Gros-œuvre'), ('Jardin', 'Jardin'), ('Divers', 'Divers')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='material',
            field=models.CharField(choices=[('Metal', 'Métal'), ('Plastic', 'Plastique'), ('Wood', 'Bois'), ('Glass', 'Verre'), ('Liquid', 'Liquide'), ('Powders', 'Poudre'), ('Stones', 'Pierre'), ('Others', 'Autres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='weight',
            field=models.CharField(choices=[('Moins de 1kg', 'Moins de 1kg'), ('Entre 1kg et 5kg', 'Entre 1kg et 5kg'), ('Entre 5kg et 10kg', 'Entre 5kg et 10kg'), ('Entre 10kg et 20kg', 'Entre 10kg et 20kg'), ('Entre 20kg et 50kg', 'Entre 20kg et 50kg'), ('Entre 50kg et 100kg', 'Entre 50kg et 100kg'), ('Plus de 100kg', 'Plus de 100kg')], max_length=30),
        ),
    ]
