# Generated by Django 4.2.5 on 2023-09-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_scrap_category_alter_scrap_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='material',
            field=models.CharField(choices=[('Métal', 'Métal'), ('Plastique', 'Plastique'), ('Bois', 'Bois'), ('Verre', 'Verre'), ('Liquide', 'Liquide'), ('Poudre', 'Poudre'), ('Pierres', 'Pierres'), ('Autres', 'Autres')], max_length=20),
        ),
    ]
