# Generated by Django 4.2.5 on 2023-09-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_scrap_category_alter_scrap_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='quantity',
        ),
        migrations.AddField(
            model_name='scrap',
            name='photo1',
            field=models.ImageField(default='Some Default Photo', upload_to='scraps_photos/'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='photo2',
            field=models.ImageField(blank=True, default='Some Default Photo', null=True, upload_to='scraps_photos/'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='photo3',
            field=models.ImageField(blank=True, default='Some Default Photo', null=True, upload_to='scraps_photos/'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='photo4',
            field=models.ImageField(blank=True, default='Some Default Photo', null=True, upload_to='scraps_photos/'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='photo5',
            field=models.ImageField(blank=True, default='Some Default Photo', null=True, upload_to='scraps_photos/'),
        ),
    ]
