# Generated by Django 4.2.5 on 2023-09-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_scrap_quantity_scrap_photo1_scrap_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='photo1',
            field=models.ImageField(default=None, upload_to='scraps_photos/'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='photo2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='scraps_photos/'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='photo3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='scraps_photos/'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='photo4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='scraps_photos/'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='photo5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='scraps_photos/'),
        ),
    ]
