# Generated by Django 4.2.5 on 2023-09-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_scrap_photo1_alter_scrap_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='sending',
            field=models.BooleanField(default=False),
        ),
    ]
