# Generated by Django 4.2.5 on 2023-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_scrap_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
