# Generated by Django 4.2.5 on 2023-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_usercustom_email_alter_usercustom_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Adresse e-mail déjà utilisée!'}, max_length=254, unique=True),
        ),
    ]
