# Generated by Django 4.2.5 on 2023-10-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_usercustom_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur est déjà inscrit avec cette adresse e-mail.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Un utilisateur est déjà inscrit avec ce numéro de téléphone.'}, max_length=15, unique=True),
        ),
    ]
