# Generated by Django 4.2.5 on 2023-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_scrap_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
