# Generated by Django 4.2.5 on 2023-10-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_scrap_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='home_pickup',
            new_name='homePickup',
        ),
    ]
